server.port = 8081
spring.application.name = newsService
logging.level.org.springframework.web: DEBUG
spring.data.mongodb.uri= mongodb://localhost:27017/NewsDB

news.api.url=https://newsapi.org/v2/top-headlines
news.api.country=us
news.api.category=technology
news.api.key=71a2d5b0f83f460b890e3202b1f1fc55