server.port = 8081
spring.application.name = newsService
logging.level.org.springframework.web: DEBUG

spring.config.import=aws-parameterstore:/config/NewsService/
spring.data.mongodb.uri= ${MongoDbURI}
spring.redis.port = 6379
spring.redis.host = localhost
spring.cache.redis.time-to-live = 600000