url=jdbc:mysql://localhost:3306/user_db
username=root
password=12345
driver=com.mysql.cj.jdbc.Driver

classpath=E:/Software/mysql-connector-java-8.0.28.jar
changeLogFile=userService/src/main/resources/db/changelog/db.changelog-master.xml

logLevel=INFO
