server.port = 8083
spring.application.name = contentService

spring.config.import=aws-parameterstore:/config/contentService/

security.oauth2.client.registration.google.client-id= your-github-client-id
spring.security.oauth2.client.registration.google.client-secret= your-github-client-secret
spring.security.oauth2.client.registration.google.redirect-uri=${redirect_uri}