server.port = 8083
spring.application.name = contentService

spring.config.import=aws-parameterstore:/config/contentService/

spring.security.oauth2.client.registration.google.client-id=${client_id}
spring.security.oauth2.client.registration.google.client-secret=${client_secret}
spring.security.oauth2.client.registration.google.redirect-uri=${redirect_uri}