server.port = 8083
spring.application.name = contentService

spring.config.import=aws-parameterstore:/config/contentService/

spring.security.oauth2.client.registration.google.client-id=416932648493-k8tsefafa6jlmnbr3enppnt2nh84pg2e.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8083/login/oauth2/code/google